"""Add stuff

Revision ID: 7f153b3ad3fc
Revises: 
Create Date: 2021-05-10 18:45:54.635077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f153b3ad3fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_number', sa.BigInteger(), nullable=False),
    sa.Column('rn', sa.Text(), nullable=False),
    sa.Column('created_by', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('assignee_email', sa.Text(), nullable=True),
    sa.Column('drug_ndc', sa.Text(), nullable=False),
    sa.Column('original_case_number', sa.BigInteger(), nullable=True),
    sa.Column('original_case_relationship', sa.Text(), nullable=True),
    sa.CheckConstraint('(original_case_number is not null and original_case_relationship is not null) or (original_case_number is null and original_case_relationship is null)'),
    sa.ForeignKeyConstraint(['original_case_number'], ['cases.case_number'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('case_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    # ### end Alembic commands ###
